---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Dylan Malandain.
--- DateTime: 22/04/2019 01:54
---

---@type table
ItemsWrapper = {}

function ItemsWrapper.ItemsDescription(CurrentMenu, SettingsDescription, Description, Selected)
    if Selected and CurrentMenu.Description ~= Description then

        CurrentMenu.Description = Description or nil

        ---@type number
        local DescriptionLineCount = RageUI.GetLineCount(CurrentMenu.Description, CurrentMenu.X + SettingsDescription.Text.X, CurrentMenu.Y + SettingsDescription.Text.Y + CurrentMenu.SubtitleHeight + RageUI.ItemOffset, 0, SettingsDescription.Text.Scale, 255, 255, 255, 255, nil, false, false, SettingsDescription.Background.Width + CurrentMenu.WidthOffset)

        if DescriptionLineCount > 1 then
            CurrentMenu.DescriptionHeight = SettingsDescription.Background.Height * DescriptionLineCount
        else
            CurrentMenu.DescriptionHeight = SettingsDescription.Background.Height + 7
        end
    end
end

function ItemsWrapper.SelectedSound(CurrentMenu, Hovered, Selected, Submenu)
    if Selected and (CurrentMenu.Controls.Select.Active or (Hovered and CurrentMenu.Controls.Click.Active)) then
        RageUI.PlaySound(RageUI.Settings.Audio.Library, RageUI.Settings.Audio.Select)
        if Submenu ~= nil then
            if Submenu() then
                RageUI.NextMenu = Submenu
            end
        end
    end
end