---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Dylan Malandain.
--- DateTime: 03/10/2019 18:37
---

TimerBar = {}

RageUI.ItemOffset = 0

TimerBar.Settings = {

}

function TimerBar.Visible()

end

function TimerBar.Background()

end

function TimerBar.Render()

end