---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Dylan Malandain.
--- DateTime: 03/10/2019 19:20
---

---@type table
UITimerBarItem = setmetatable({}, UITimerBarItem)

---@type table
UITimerBarItem.__index = UITimerBarItem

---@type table
UITimerBarItem.__call = function()
    return "UITimerBarItem"
end

function UITimerBarItem.New(Text, SecondText, TextureDictionary, TextureName, Heading, R, G, B, A)
    Heading = tonumber(Heading) or 0
    R = tonumber(R) or 255
    G = tonumber(G) or 255
    B = tonumber(B) or 255
    A = tonumber(A) or 200
    local _UITimerBarItem = {
        Background = { Dictionary = TextureDictionary or "timerbars", Texture = TextureName or "all_black_bg", Color = { R = R, G = G, B = B, A = A } },
        Text = Text or "",
        SecondText = SecondText or "",
        Position = { X = 1540, Y = 1060 },
    }
    return setmetatable(_UITimerBarItem, UITimerBarItem)
end

function UITimerBarItem:Visible(Pool, Value)
    if Value then
        table.insert(Pool.BarVisible, self)
    else
        for i = 1, #Pool.BarVisible, 1 do
            if Pool.BarVisible[i] == self then
                table.remove(Pool.BarVisible, i)
                break
            end
        end
    end
end

function UITimerBarItem:SetSecondText(Text)
    self.SecondText = tostring(Text)
end

function UITimerBarItem:Draw(Interval)
    RenderSprite(self.Background.Dictionary, self.Background.Texture, self.Position.X, self.Position.Y - Interval, 350, 35, 0, 0, 0, 0, 255)
    RenderText(self.Text, self.Position.X + 170.0, self.Position.Y - Interval + 7.0, 0, 0.35, 255, 255, 255, 255, "Right")
    RenderText(self.SecondText, self.Position.X + 340.0, self.Position.Y - Interval, 0, 0.45, 255, 255, 255, 255, "Right")
end