---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Dylan Malandain.
--- DateTime: 20/12/2019 19:07
---

local mainMenu = RageUI.CreateMenu("RageUI", "Undefined for using SetSubtitle")
mainMenu:SetSubtitle("~b~RageUI SHOWCASE")
mainMenu.EnableMouse = true;
mainMenu.Closed = function()
    -- TODO Perform action
end;

local submenu = RageUI.CreateSubMenu(mainMenu, "RageUI", "~b~RAGEUI SHOWCASE", nil, nil, "casinoui_roulette_high", "casinoui_roulette_high")

RageUI.CreateWhile(1.0, function()

    if IsControlJustPressed(1, 51) then
        RageUI.Visible(mainMenu, not RageUI.Visible(mainMenu))
    end

    if RageUI.Visible(mainMenu) then
        RageUI.DrawContent({ header = true, glare = true, instructionalButton = true }, function()
            ---Items
        end, function()
            ---Panels
        end)
    end

    if RageUI.Visible(submenu) then
        RageUI.DrawContent({ header = true, glare = true, instructionalButton = true }, function()
            ---Items
        end, function()
            ---Panels
        end)
    end

end, 1)